// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJElchb5ktKjKVBTi5Cp1lHc3NuZCq28',
    appId: '1:301100606739:web:43e3bb07cfcb9ff68226e6',
    messagingSenderId: '301100606739',
    projectId: 'aieats-96da7',
    authDomain: 'aieats-96da7.firebaseapp.com',
    storageBucket: 'aieats-96da7.appspot.com',
    measurementId: 'G-GXS7NZLT23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9vZyjdI-oyTBrFsOZgG9lSuqRKIEtEGc',
    appId: '1:301100606739:android:c0b4a7dd988c59658226e6',
    messagingSenderId: '301100606739',
    projectId: 'aieats-96da7',
    storageBucket: 'aieats-96da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1R4eCzt0-QY8ogg4-g-dGuRs1AmmaOQ',
    appId: '1:301100606739:ios:746623267c4161ac8226e6',
    messagingSenderId: '301100606739',
    projectId: 'aieats-96da7',
    storageBucket: 'aieats-96da7.appspot.com',
    iosClientId: '301100606739-hghndg3s9d4f7d94ek364jhlkgph6g27.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo1R4eCzt0-QY8ogg4-g-dGuRs1AmmaOQ',
    appId: '1:301100606739:ios:0e2c1e88d65764548226e6',
    messagingSenderId: '301100606739',
    projectId: 'aieats-96da7',
    storageBucket: 'aieats-96da7.appspot.com',
    iosClientId: '301100606739-6hbpugagdpco9ip0vpoiku3p6u3rv7b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiEats.RunnerTests',
  );
}
